# Node.js ka base image lo (version 18)
FROM node:18-alpine

# Container ke andar kaam karne ki jagah (folder) set karo
WORKDIR /app

# package.json aur package-lock.json copy karo
COPY package*.json ./

# Dependencies install karo
RUN npm install

# Baaki saara code copy karo
COPY . .

# Port expose karo (jis par backend chalega)
EXPOSE 5000

# Container start karne ka command
CMD ["npm", "start"]