apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ansh331/task-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: mongodb://mongodb-service:27017/taskdb
        - name: JWT_SECRET
          value: mySuperSecretKey123
