name: Test Docker Login

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Secret Length
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Username: $USERNAME"
          echo "Username Length: ${#USERNAME}"
          echo "Token Length: ${#TOKEN}"

      - name: Docker Login
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$TOKEN" | docker login -u "$USERNAME" --password-stdin

      - name: Check Login
        run: docker info
