name: Test Docker Login

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Secret Info
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Username: '$USERNAME'"
          echo "Username Length: ${#USERNAME}"
          echo "Token Length: ${#TOKEN}"

      - name: Login using Docker CLI
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$TOKEN" | docker login docker.io --username "$USERNAME" --password-stdin

      - name: Pull Test Image
        run: |
          docker pull hello-world

      - name: Show Docker Info
        run: docker info
